version: '2.4'
services:
    start_dependencies:
        image: "dadarek/wait-for-dependencies"
        depends_on:
            - "keycloak"
        command: keycloak:8080
    keycloak:
        image: "jboss/keycloak:latest"
        container_name: keycloak
        environment:
            - "KEYCLOAK_USER=${KEYCLOAK_USER}"
            - "KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}"
            - "KEYCLOAK_IMPORT=${KEYCLOAK_IMPORT}"
        ports:
            - "8080:8080"
        volumes:
            - "/Users/admin/keycloak/realm.json:/tmp/realm.json"
    novaas:
        build: .
        image: "registry.gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas-keycloak:latest"
        container_name: novaas
        environment:
            - "PORT_FORWARDING=${PORT_FORWARDING}" 
            - "HOST=${HOST}"
            - "BROKER_SERVICE_HOST=${BROKER_SERVICE_HOST}"
            - "BROKER_SERVICE_PORT=${BROKER_SERVICE_PORT}"
            - "REPO_LOCATION=${REPO_LOCATION}"
            - "SECURITY_SHELL_ID=${SECURITY_SHELL_ID}"
            - "SECURITY_SETTINGS_SUBMODEL_ID=${SECURITY_SETTINGS_SUBMODEL_ID}"
            - "SECURITY_METAMODEL_SUBMODEL_ID=${SECURITY_METAMODEL_SUBMODEL_ID}"
            - "KEYCLOAK_REALM=${KEYCLOAK_REALM}"
            - "KEYCLOAK_URL=${KEYCLOAK_URL}"
        ports:
            - "${PORT_FORWARDING}:1880"