version: '2.4'
services:
    start_dependencies:
        image: "dadarek/wait-for-dependencies"
        depends_on:
            - "keycloak"
        command: keycloak:8080
    keycloak:
        image: "jboss/keycloak:latest"
        environment:
            - "KEYCLOAK_USER=${KEYCLOAK_USER}"
            - "KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}"
            - "KEYCLOAK_IMPORT=${KEYCLOAK_IMPORT}"
        ports:
            - "8080:8080"
        volumes:
            - "/Users/admin/keycloak/realm.json:/tmp/realm.json"
    novaas:
        build: .
        image: "novaas/keycloak/dockerbase:1.0.0"
        environment:
            - "PORT_FORWARDING=${PORT_FORWARDING}" 
            - "HOST=${HOST}"
            - "BROKER_SERVICE_HOST=${BROKER_SERVICE_HOST}"
            - "BROKER_SERVICE_PORT=${BROKER_SERVICE_PORT}"
            - "KEYCLOAK_REALM=${KEYCLOAK_REALM}"
            - "KEYCLOAK_URL=${KEYCLOAK_URL}"
            - "KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}"
            - "KEYCLOAK_CLIENT_ID_UI=${KEYCLOAK_CLIENT_ID_UI}"
            - "KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}"
            - "KEYCLOAK_CLIENT_SECRET_UI=${KEYCLOAK_CLIENT_SECRET_UI}"
            - "KEYCLOAK_OPEN_ID=${KEYCLOAK_OPEN_ID}"
        ports:
            - "${PORT_FORWARDING}:1880"